

POST http://localhost:4000/login/
Content-Type: application/json


{
    "username": "admin",
    "password": "abc123"
}

###


POST http://localhost:4000/addCourier/
Content-Type: application/json


{
    "courierId": 61502,
    "courierName": "T-shirt",
    "fromAddress": "Eluru",
    "toAddress":"Badrachalam",
    "isDelivered": false
}

###


POST http://localhost:4000/addShipment/
Content-Type: application/json

{
    "courierID": 61503,
    "shipmentID": 25694,
    "location": "Vijayawada",
    "status":"dispatched"
}

###

GET http://localhost:4000/getTrackingData/76084


###
GET http://localhost:4000/getCourier/61504


###
DELETE http://localhost:4000/deleteShipment/


###

PUT http://localhost:4000/updateShipment/
Content-Type: application/json

{
    "courierId": 61504,
    "shipmentID": 4,
    "location": "Hyderabad",
    "status":"delivered"
}